---
pbrt_flags: ""
ffmpeg_in_flags: "-y"
ffmpeg_out_flags: "-vcodec libx264 -crf 0 -preset veryslow"
accelerator: "bvh"
camera: "perspective"
filter: "box"
integrator: "path"
sampler: "halton"
resolution: [960, 540]
frame_rate: 30
pixelsamples: 4
output: "output"
cache: "output/_cache"
filename: "output/render.png"
