---
pbrt_flags: ""
ffmpeg_in_flags: "-y"
ffmpeg_out_flags: "-vcodec libx264 -crf 0 -preset veryslow"
accelerator: "bvh"
camera: "perspective"
filter: "box"
integrator: "path"
sampler: "halton"
resolution: [640, 360]
frame_rate: 15
pixelsamples: 1
output: "output"
cache: "output/_cache"
filename: "output/render.png"
