---
pbrt_flags: "--quiet"
accelerator: "bvh"
camera: "perspective"
filter: "box"
integrator: "path"
sampler: "halton"
resolution: [240, 135]
frame_rate: 5
pixelsamples: 1
output: "test-output"
filename: "test-output/render.png"
