---
pbrt_flags: "--quiet"
ffmpeg_in_flags: "-y -v 0"
ffmpeg_out_flags: "-vcodec libx264 -crf 0 -preset veryfast"
accelerator: "bvh"
camera: "perspective"
filter: "box"
integrator: "path"
sampler: "halton"
resolution: [240, 135]
frame_rate: 5
pixelsamples: 1
output: "test-output"
filename: "test-output/render.png"
